
// 1) import monggose, we will store user information in the data base
const mongoose = require('mongoose')
// 5) some defaults errors are generated by MongoDB, but some times it is hard to solve the problem. To see error messages, we use mongoose-unique-validator
const mongooseUniqueValidator = require('mongoose-unique-validator')

// 2) create mongoose schema
const userSchema = mongoose.Schema({
    // 3) store emails and passwords
    // 4) Many users can use the same email address, so unique key word prevents this.
    email: { type: String, required: true, unique: true },
    password: { type: String, required: true }

})

userSchema.plugin(mongooseUniqueValidator);

//6 exporting the schema using the model() function
module.exports = mongoose.model('user', userSchema)